version: '3'
services:
  app: &app
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 4000
    volumes:
      - .:/opt/app
      - app-bundle:/usr/local/bundle
    ports:
      - "4000:4000"
      - "3035:3035"
    environment:
      EDITOR: vi
    env_file:
      .env
volumes:
  app-bundle: